// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpzoiwizjtfsdekerark.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwem9pd2l6anRmc2Rla2VyYXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzODc2MzksImV4cCI6MjA4MTk2MzYzOX0.uXgWE0gyHC3_EQL-fNcQjDN0DupFSU5H4HppRU1aLbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});